- name: Create us-east-1 VPC
  ec2_vpc_net:
    name: eth-vpc-us-east-1
    cidr_block: 10.10.0.0/16
    region: us-east-1
    tags:
      environment: development
      coin:        ethereum
    tenancy: default
  register: vpc

- name: us-east-1 VPC var
  set_fact:
    vpc_id: "{{ vpc.vpc.id }}"

- name: Create 1a subnet 
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc_id }}"
    cidr:             "10.10.0.0/18"
    az:               "us-east-1a"
    region:           "us-east-1"
    map_public: yes
    resource_tags:
      environment: development
      coin:        ethereum
  register: subnet_1a

- name: Create 1a subnet var
  set_fact:
    subnet_us_east_1a_id: "{{ subnet_1a.subnet.id }}"

- name: Create us-east-1 IGW
  ec2_vpc_igw:
    vpc_id:           "{{ vpc_id }}"
    region:           "us-east-1"
    state:            "present"
  register: igw_us_east_1

- name: Create us-east-1 IGW var
  set_fact:
    igw_us_east_1_id:           "{{ igw_us_east_1.gateway_id }}"

- name: Create us-east-1a route table
  ec2_vpc_route_table:
    vpc_id:           "{{ vpc_id }}"
    region:           "us-east-1"
    tags:
      Name:           "Public"
    subnets:
      - "{{ subnet_us_east_1a_id }}"
    routes:
      - dest:         "0.0.0.0/0"
        gateway_id:   "{{ igw_us_east_1_id }}"

- name:               Create Main Security Group
  ec2_group:
    name:             "My Security Group"
    description:      "My Security Group"
    vpc_id:           "{{ vpc_id }}"
    region:           "us-east-1"
    rules:
      - proto:        "tcp"
        from_port:    "22"
        to_port:      "22"
        cidr_ip:      "165.227.20.130/32"
